# Generated by Django 3.2.12 on 2022-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge_share',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU/MB/RAM', 'CPU/메인보드/램'), ('VGA', '그래픽카드'), ('CASE', '케이스'), ('SSD/HDD/USB', 'SSD/HDD/USB'), ('COOLER', '공랭/수랭쿨러'), ('POWER', '파워서플라이'), ('KEYBOARD/MOUSE', '키보드/마우스')], max_length=50),
        ),
    ]
