# Generated by Django 3.2.12 on 2022-04-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_no', models.AutoField(primary_key=True, serialize=False)),
                ('application_item', models.CharField(max_length=100)),
                ('processing', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trade_no'],
            },
        ),
    ]
