# Generated by Django 3.2.12 on 2022-04-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeal',
            name='view_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
